### ISSUE TITLE
"Issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by tkhero555** [tkhero555/runteq_graduation_exam#29]
## 事前準備
- [ ] インフラ環境構築
- [ ] docker開発環境構築

## 実装予定の機能
- [ ] Linebot
- [ ] Line連携ログイン
- [ ] ユーザー認証(ログイン)
- [ ] 食事の記録
- [ ] 便の記録
- [ ] 相関判定
- [ ] パスワードリセット
- [ ] (本リリース)レコメンド機能
- [ ] (本リリース)コメント機能
- [ ] (本リリース)検索機能
- [ ] (本リリース)カレンダー履歴表示

## 必要な画面
- [ ] Linebotトーク画面
- [ ] 全体のレイアウト
- [ ] 会員登録画面
- [ ] ログイン画面
- [ ] パスワード再設定画面
- [ ] ユーザー詳細画面(マイページ)
- [ ] プライバシーポリシー
- [ ] 利用規約
- [ ] Line連携ログイン画面

**Comment by Tsuchiya2** [comment]
Projectsにアクセスしましたが、看板・issue・ストーリーポイントが確認できませんでした。
カリキュラムをご確認の上、上記が確認できる状態でご提出をお願いいたします。

![image](https://github.com/tkhero555/runteq_graduation_exam/assets/61481161/49dc6ec4-090a-4f23-8cd0-c8fb3dfb7e2f)

**Comment by tkhero555** [comment]
作成したprojectを卒業制作用のリポジトリにリンクしました。
再度、ご確認ください。

**Comment by kenchasonakai** [comment]
LGTMです！
